#!/bin/bash

set -ex

# uncomment the 2nd background parameter to enable transparency.
montage \
    -label %t \
    -pointsize 50 \
    -fill Gray \
    -geometry +100+100 \
    -background 'rgba(0,0,0,0)' \
    -background '#e1e1e1' \
    "$@"

optipng "${@: -1}"
