#!/bin/bash

set -e

printf "\n\033[32m%s\033[0m\n" $1

# necessary for admesh in ubuntu 18.04
export LD_LIBRARY_PATH=/usr/local/lib

name=$(basename -s .scad $1)
dirname=$(dirname $1)
tmp_stl=tmp/${name}.$$.stl
final_stl=dist/${dirname}/${name}.stl
final_report=dist/${dirname}/${name}.txt

mkdir -p tmp
mkdir -p dist/$dirname

openscad --hardwarnings $1 -o ${tmp_stl}

# https://pypi.org/project/numpy-stl/
# convert to binary (1/5 size, quicker loading)
# https://github.com/admesh/admesh
# https://github.com/admesh/admesh/releases/download/v0.98.4/admesh-0.98.4.tar.gz

#stl2bin tmp/${name}.$$.stl dist/${name}.stl
admesh --write-binary-stl=${final_stl} ${tmp_stl} > ${final_report}
rm ${tmp_stl}

# make PNG images (transparent background, anti-aliased)
./stl2png ${final_stl}
